Func = PhoneBook.cpp

Flags = -Wall -Wextra -Werror -std=c++98

CC = c++

name = phoneBook

all: $(name)

$(name) :
	$(CC) $(Flags) $(Func) -o $(name)

clean:

fclean:
	rm -rf $(name)

re : fclean all
