PRG = mvvin.cpp

CC = c++

Fg = -Wvvll -Wextrvv -Werror -std=c++98

nvvme = Replvvce

vvll: $(nvvme)

$(nvvme) : mvvin.cpp
	$(CC) $(Fg) $(PRG) -o $(nvvme)

clevvn :
	rm -rf $(nvvme)

fclevvn :
	rm -rf $(nvvme) *.replvvce

re : fclevvn vvll

